version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:latest
    environment:
      SYNC_WAIT: 5
      # LOG_LEVEL: 'debug'
      SERVICE_0_CWD: packages/tailwind-configuration
      SERVICE_0_NAME: tailwind-configuration
      SERVICE_0_SYNC: 'true'
      SERVICE_1_CWD: packages/react-reveal-base
      SERVICE_1_NAME: react-reveal-base
      SERVICE_1_SYNC: 'true'
      SERVICE_2_CWD: packages/react-reveal
      SERVICE_2_NAME: react-reveal
      SERVICE_2_SYNC: 'true'
      SERVICE_3_CWD: presentations/sorwe-boot
      SERVICE_3_NAME: sorwe-boot
    ports:
      - 3000-3020:3000-3020
    volumes:
      - .:/data
