version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:latest
    environment:
      SYNC_WAIT: 10
      SERVICE_0_CWD: packages/tailwind-configuration
      SERVICE_0_NAME: tailwind-configuration
      SERVICE_0_SYNC: 'true'
      SERVICE_1_CWD: packages/reveal
      SERVICE_1_NAME: react-reveal
      SERVICE_1_SYNC: 'true'
      SERVICE_2_CWD: presentations/sorwe-boot
      SERVICE_2_NAME: sorwe-boot
    ports:
      - 3000-3020:3000-3020
    volumes:
      - .:/data
